"""empty message

Revision ID: 464950a92805
Revises: b0a4fc14f327
Create Date: 2020-05-14 19:37:39.373868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464950a92805'
down_revision = 'b0a4fc14f327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
